version: '2'
services:
  php:
    image: yiisoftware/yii2-php:8.0-apache
    restart: unless-stopped
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
      - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    ports:
      - '9000:80'
    env_file:
      - .env
  mariadb:
    image: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: